### ISSUE TITLE
Can't resolve dc_datatables

### ISSUE THREAD

**Issue by jackcrymble** [dc-js/dc.datatables.js#1] opened 2018-10-04 09:49 UTC
I am trying to integrate this package with my existing project but am currently unable to correctly import due to a ' ERROR in ./node_modules/dc.datatables/dc.datatables.js' where it cannot resolve dc_datatables.
![datatables_error](https://user-images.githubusercontent.com/11898127/46466130-5a74ff80-c7c2-11e8-8fc0-5089c208f5f9.png)

By importing in a similar way to dc :
`import * as dctable from 'dc.datatables';`), i get a 'cannot find module' error.

By importing the file directly:
(`import * as dctable from 'dc.datatables/dc.datatables'`) the 'Can't resolve dc_datatables error is produced.

**Comment by gordonwoodhull** [comment] 2018-10-04 15:31
Hi @jackcrymble, thanks for the report!

Unfortunately I have not tested this package in ES6. I still live in an ES5 world and don't transpile any of my packages. I know that it works well with AMD. 😕 

Would you be able to create a minimal example for me to test with?

**Comment by jackcrymble** [comment] 2018-10-04 17:22
Hi @gordonwoodhull!

Thanks for the quick reply!

I have been unable to reproduce the issue on stackblitz, however I have created a repo for you to clone with the issue. https://github.com/jackcrymble/reproduction

The reproduction steps are very basic:
1. Create a new Angular 6 Project (ng new <name>)
2. Install dc.datatables (npm install --save dc.datatables)
3. In the generated app.component.ts file import dc.datatables (import * as dctable from 'dc.datatables/dc.datatables';)
4. Try to use the import such as a console log of dctable as in my example. (console.log(dctable);)

Versions:
Angular: 6.1.9
Angular CLI: 6.1.5
NPM: 6.4.1
Node: 10.8.0
OS: linux x64 (Ubuntu 18.04.1)

**Comment by gordonwoodhull** [comment] 2018-10-04 19:40
Thanks @jackcrymble! The repo seemed to be blank but I was able to repro using your clear instructions.

Always interesting to try out a new web platform - there are so many.

Turns out the AMD was not valid (it was trying to import itself!) and also it needed the `main` entry point in `package.json` - should be fixed for all ES6 & Typescript now in 0.0.4

**Comment by gordonwoodhull** [comment] 2018-10-04 19:40
This is a brand new package (obviously) so any contributions are welcome. The main point is to show an efficient way to get data into datatables.js since a lot of people were hacking this via [dc.dataTable](https://dc-js.github.io/dc.js/docs/html/dc.dataTable.html). 

I hope that most customization can be done via the exposed datatable object `datatable.dt()`

The columns format loosely follows [what dc.dataTable expects](https://dc-js.github.io/dc.js/docs/html/dc.dataTable.html#columns__anchor). We'll probably want to move beyond that, so if you run into column type problems, please raise another issue.

**Comment by jackcrymble** [comment] 2018-10-05 13:54
Hi @gordonwoodhull 

I've installed the new changes, and the dc_datatables error appears to be fixed. However, there is a new issue with the import of crossfilter.

![crossfilter_not_defined](https://user-images.githubusercontent.com/11898127/46539501-8ec5ea00-c8ae-11e8-86de-09f52b602dfb.png)
^ Taken from debugger logs on Chrome ^

Any thoughts on this?

**Comment by gordonwoodhull** [comment] 2018-10-05 14:17
Thanks @jackcrymble! Clearly I need to test end-to-end in an ES6 environment.

I'll use Observable. I'm able to reproduce the problem here: https://beta.observablehq.com/d/2063842a8e361385

Hope to fix this later today, if time allows.

**Comment by gordonwoodhull** [comment] 2018-10-05 16:07
The library has four direct dependencies: d3, dc, jquery, datatables, published as 0.0.6

It tests correctly in the observable notebook above, which should mean it is now compatible with all ES6 environments including Typescript.

Thanks for your patience @jackcrymble - please lmk if you run into further problems!

**Closed by gordonwoodhull** 2018-10-05 16:07 UTC
Labels: bug

**Comment by gordonwoodhull** [comment] 2018-10-09 13:17
For future testing, I created a repo here: https://github.com/dc-js/ang-dctable
